-- RaiseReady database setup. Paste ALL of this into the Supabase SQL Editor and click Run.
-- Generated by scripts/build-setup-sql.sh from supabase/migrations. Safe to run more than once.

-- ===== 20261001000100_helpers.sql =====
-- Shared helpers used by every table.

create extension if not exists pgcrypto with schema extensions;

-- Functions that RLS policies call live in a schema that is not exposed
-- through the PostgREST API.
create schema if not exists private;
grant usage on schema private to authenticated, service_role;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ===== 20261001000200_schema.sql =====
-- Core RaiseReady schema (spec section 5).
-- Enumerations are text + check constraints so they can be extended by later
-- migrations without enum-type rewrites.

------------------------------------------------------------------------------
-- profiles: one row per auth user, created automatically on sign-up.
------------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  country text,
  role text not null default 'founder' check (role in ('founder', 'admin')),
  plan text not null default 'free' check (plan in ('free', 'pro')),
  credits integer not null default 0 check (credits >= 0),
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

------------------------------------------------------------------------------
-- startups
------------------------------------------------------------------------------
create table if not exists public.startups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 200),
  website text,
  industry text,
  country text,
  stage text check (stage in ('idea', 'pre_seed', 'seed', 'series_a', 'other')),
  founding_year integer check (founding_year between 1900 and 2100),
  business_model text,
  revenue_monthly numeric(18, 2) check (revenue_monthly >= 0),
  revenue_currency char(3) not null default 'NGN',
  customers_count integer check (customers_count >= 0),
  growth_notes text,
  raising boolean not null default false,
  amount_seeking numeric(18, 2) check (amount_seeking >= 0),
  seeking_currency char(3) not null default 'NGN',
  funding_type text check (funding_type in ('equity', 'safe', 'convertible_note', 'grant', 'debt', 'other')),
  previously_raised boolean,
  use_of_funds text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists startups_owner_id_idx on public.startups (owner_id);

------------------------------------------------------------------------------
-- documents
------------------------------------------------------------------------------
create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  kind text not null check (kind in ('pitch_deck', 'financial_model', 'business_plan', 'other')),
  original_filename text,
  storage_path text not null unique,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 20 * 1024 * 1024),
  status text not null default 'uploaded' check (status in ('uploaded', 'processing', 'ready', 'failed')),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists documents_startup_id_idx on public.documents (startup_id);

------------------------------------------------------------------------------
-- knowledge_profiles: versioned structured extraction (spec 6.1)
------------------------------------------------------------------------------
create table if not exists public.knowledge_profiles (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  version integer not null check (version > 0),
  data jsonb not null,
  source_document_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (startup_id, version)
);

------------------------------------------------------------------------------
-- assessments (spec 6.2)
------------------------------------------------------------------------------
create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  knowledge_profile_id uuid references public.knowledge_profiles (id) on delete set null,
  overall_score integer not null check (overall_score between 0 and 100),
  band text not null check (band in ('not_ready', 'getting_there', 'nearly_ready', 'investor_ready')),
  dimension_scores jsonb not null,
  strengths jsonb not null default '[]',
  weaknesses jsonb not null default '[]',
  recommended_actions jsonb not null default '[]',
  rubric_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists assessments_startup_id_created_at_idx on public.assessments (startup_id, created_at desc);
create index if not exists assessments_knowledge_profile_id_idx on public.assessments (knowledge_profile_id);

------------------------------------------------------------------------------
-- simulations (spec 6.3)
------------------------------------------------------------------------------
create table if not exists public.simulations (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  persona text not null check (persona in ('seed_vc', 'angel', 'grant_evaluator')),
  difficulty text not null check (difficulty in ('friendly', 'analytical', 'tough')),
  funding_type text,
  status text not null default 'active' check (status in ('active', 'completed', 'abandoned')),
  current_round integer not null default 1 check (current_round between 1 and 10),
  overall_score integer check (overall_score between 0 and 100),
  investor_confidence text check (investor_confidence in ('low', 'medium', 'high')),
  final_evaluation jsonb,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists simulations_startup_id_created_at_idx on public.simulations (startup_id, created_at desc);

create table if not exists public.simulation_turns (
  id uuid primary key default gen_random_uuid(),
  simulation_id uuid not null references public.simulations (id) on delete cascade,
  turn_index integer not null check (turn_index >= 0),
  round integer not null check (round between 1 and 10),
  role text not null check (role in ('investor', 'founder', 'system')),
  content text not null,
  evaluation jsonb,
  red_flags jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (simulation_id, turn_index)
);

create table if not exists public.red_flags (
  id uuid primary key default gen_random_uuid(),
  simulation_id uuid not null references public.simulations (id) on delete cascade,
  turn_id uuid references public.simulation_turns (id) on delete cascade,
  type text not null check (type in ('contradiction', 'unsupported_claim', 'weak_answer', 'missing_info')),
  severity text not null check (severity in ('low', 'medium', 'high')),
  description text not null,
  evidence jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists red_flags_simulation_id_idx on public.red_flags (simulation_id);
create index if not exists red_flags_turn_id_idx on public.red_flags (turn_id);

------------------------------------------------------------------------------
-- reports (spec 6.4)
------------------------------------------------------------------------------
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  assessment_id uuid references public.assessments (id) on delete set null,
  simulation_id uuid references public.simulations (id) on delete set null,
  content jsonb not null,
  pdf_storage_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists reports_startup_id_idx on public.reports (startup_id);
create index if not exists reports_assessment_id_idx on public.reports (assessment_id);
create index if not exists reports_simulation_id_idx on public.reports (simulation_id);

------------------------------------------------------------------------------
-- payments & subscriptions (spec 7). Written only by the server.
------------------------------------------------------------------------------
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  provider text not null default 'paystack' check (provider in ('paystack')),
  reference text not null unique,
  amount_kobo bigint not null check (amount_kobo >= 0),
  currency char(3) not null default 'NGN',
  product text not null check (product in ('pro_monthly', 'credits_3', 'credits_10')),
  status text not null default 'pending' check (status in ('pending', 'success', 'failed', 'abandoned', 'reversed')),
  raw_event jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists payments_user_id_idx on public.payments (user_id);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  provider_subscription_code text unique,
  status text not null check (status in ('active', 'non_renewing', 'attention', 'cancelled', 'completed')),
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists subscriptions_user_id_idx on public.subscriptions (user_id);

------------------------------------------------------------------------------
-- ai_calls: cost tracking. user_id is nulled on account deletion so aggregate
-- cost history survives without being linked to a person. No founder content
-- is stored here.
------------------------------------------------------------------------------
create table if not exists public.ai_calls (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles (id) on delete set null,
  purpose text not null,
  model text not null,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  latency_ms integer check (latency_ms >= 0),
  success boolean not null,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ai_calls_user_id_created_at_idx on public.ai_calls (user_id, created_at desc);
create index if not exists ai_calls_created_at_idx on public.ai_calls (created_at desc);

------------------------------------------------------------------------------
-- audit_logs: survives actor deletion (actor_id is nulled).
------------------------------------------------------------------------------
create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles (id) on delete set null,
  action text not null,
  target_type text,
  target_id uuid,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists audit_logs_actor_id_idx on public.audit_logs (actor_id);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);

------------------------------------------------------------------------------
-- updated_at triggers on every table
------------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'startups', 'documents', 'knowledge_profiles', 'assessments',
    'simulations', 'simulation_turns', 'red_flags', 'reports', 'payments',
    'subscriptions', 'ai_calls', 'audit_logs'
  ] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format(
      'create trigger set_updated_at before update on public.%I
         for each row execute function private.set_updated_at()', t);
  end loop;
end;
$$;

------------------------------------------------------------------------------
-- Create a profile automatically when an auth user signs up.
------------------------------------------------------------------------------
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, nullif(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

-- ===== 20261001000300_rls.sql =====
-- Row Level Security (spec section 8).
--
-- Access model:
--   * Founders (role `authenticated`) can only see rows they own.
--   * Founders may directly write only what they author: their profile's
--     editable fields, their startups, and their document records.
--   * Everything derived by the app (extractions, scores, simulations,
--     reports), all billing state, AI usage and audit logs are written only by
--     server code using the service role, which bypasses RLS.
--   * Admin views read through the service role on the server; there are no
--     admin RLS policies, so an `admin` profile gets no extra access from the
--     browser.
--   * `anon` has no table access at all.

------------------------------------------------------------------------------
-- Ownership helpers. SECURITY DEFINER so policies on child tables do not
-- recurse through the startups policy; each checks auth.uid() explicitly.
------------------------------------------------------------------------------
create or replace function private.owns_startup(p_startup_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.startups s
    where s.id = p_startup_id and s.owner_id = (select auth.uid())
  );
$$;

create or replace function private.owns_simulation(p_simulation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.simulations sim
    join public.startups s on s.id = sim.startup_id
    where sim.id = p_simulation_id and s.owner_id = (select auth.uid())
  );
$$;

revoke all on function private.owns_startup(uuid) from public;
revoke all on function private.owns_simulation(uuid) from public;
grant execute on function private.owns_startup(uuid) to authenticated;
grant execute on function private.owns_simulation(uuid) to authenticated;
revoke all on function private.set_updated_at() from public;
revoke all on function private.handle_new_user() from public;

------------------------------------------------------------------------------
-- Enable RLS everywhere and reset privileges to least privilege.
------------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'startups', 'documents', 'knowledge_profiles', 'assessments',
    'simulations', 'simulation_turns', 'red_flags', 'reports', 'payments',
    'subscriptions', 'ai_calls', 'audit_logs'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant all on public.%I to service_role', t);
  end loop;
end;
$$;

------------------------------------------------------------------------------
-- profiles: read own; update only non-privileged columns.
-- role, plan and credits can never be changed from the browser.
------------------------------------------------------------------------------
grant select on public.profiles to authenticated;
grant update (full_name, country, onboarding_complete) on public.profiles to authenticated;

drop policy if exists "profiles: owner can read" on public.profiles;
create policy "profiles: owner can read"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()));

drop policy if exists "profiles: owner can update" on public.profiles;
create policy "profiles: owner can update"
  on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

------------------------------------------------------------------------------
-- startups: full CRUD on own rows.
------------------------------------------------------------------------------
grant select, insert, update, delete on public.startups to authenticated;

drop policy if exists "startups: owner can read" on public.startups;
create policy "startups: owner can read"
  on public.startups for select to authenticated
  using (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can insert" on public.startups;
create policy "startups: owner can insert"
  on public.startups for insert to authenticated
  with check (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can update" on public.startups;
create policy "startups: owner can update"
  on public.startups for update to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can delete" on public.startups;
create policy "startups: owner can delete"
  on public.startups for delete to authenticated
  using (owner_id = (select auth.uid()));

------------------------------------------------------------------------------
-- documents: read and delete own. Inserts and status updates happen on the
-- server after the file's content type has been validated.
------------------------------------------------------------------------------
grant select, delete on public.documents to authenticated;

drop policy if exists "documents: owner can read" on public.documents;
create policy "documents: owner can read"
  on public.documents for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "documents: owner can delete" on public.documents;
create policy "documents: owner can delete"
  on public.documents for delete to authenticated
  using ((select private.owns_startup(startup_id)));

------------------------------------------------------------------------------
-- Derived, startup-scoped data: read-only for the owner.
------------------------------------------------------------------------------
grant select on public.knowledge_profiles, public.assessments,
  public.simulations, public.reports to authenticated;

drop policy if exists "knowledge_profiles: owner can read" on public.knowledge_profiles;
create policy "knowledge_profiles: owner can read"
  on public.knowledge_profiles for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "assessments: owner can read" on public.assessments;
create policy "assessments: owner can read"
  on public.assessments for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "simulations: owner can read" on public.simulations;
create policy "simulations: owner can read"
  on public.simulations for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "reports: owner can read" on public.reports;
create policy "reports: owner can read"
  on public.reports for select to authenticated
  using ((select private.owns_startup(startup_id)));

grant select on public.simulation_turns, public.red_flags to authenticated;

drop policy if exists "simulation_turns: owner can read" on public.simulation_turns;
create policy "simulation_turns: owner can read"
  on public.simulation_turns for select to authenticated
  using ((select private.owns_simulation(simulation_id)));

drop policy if exists "red_flags: owner can read" on public.red_flags;
create policy "red_flags: owner can read"
  on public.red_flags for select to authenticated
  using ((select private.owns_simulation(simulation_id)));

------------------------------------------------------------------------------
-- Billing: read own history; written only by the server (Paystack webhook).
------------------------------------------------------------------------------
grant select on public.payments, public.subscriptions to authenticated;

drop policy if exists "payments: owner can read" on public.payments;
create policy "payments: owner can read"
  on public.payments for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "subscriptions: owner can read" on public.subscriptions;
create policy "subscriptions: owner can read"
  on public.subscriptions for select to authenticated
  using (user_id = (select auth.uid()));

-- ai_calls and audit_logs: no policies => no access except service role.

-- ===== 20261001000400_storage.sql =====
-- Private storage buckets (spec sections 3, 6.5, 8).
-- Object paths are `{owner_id}/{startup_id}/{file}` so ownership can be
-- checked from the first path segment.
-- Uploads and deletes go through server code (service role) after content
-- validation; founders may only read their own objects, which is what creating
-- a short-lived signed URL with their session requires.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('documents', 'documents', false, 20971520, array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]),
  ('reports', 'reports', false, 20971520, array['application/pdf'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "documents bucket: owner can read" on storage.objects;
create policy "documents bucket: owner can read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "reports bucket: owner can read" on storage.objects;
create policy "reports bucket: owner can read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'reports'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- ===== 20261001000500_admin.sql =====
-- Admin role seeding. Admin access is enforced server-side by checking
-- profiles.role; this function is the supported way to grant it.
-- Run from the Supabase SQL editor (as postgres):
--   select private.set_user_role('you@example.com', 'admin');
-- or with `npm run db:seed-admin -- you@example.com`.

create or replace function private.set_user_role(p_email text, p_role text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
begin
  if p_role not in ('founder', 'admin') then
    raise exception 'invalid role: %', p_role;
  end if;

  select u.id into v_user_id
  from auth.users u
  where lower(u.email) = lower(p_email);

  if v_user_id is null then
    raise exception 'no user with email %', p_email;
  end if;

  update public.profiles set role = p_role where id = v_user_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (null, 'profile.role_changed', 'profile', v_user_id, jsonb_build_object('role', p_role));

  return v_user_id;
end;
$$;

revoke all on function private.set_user_role(text, text) from public;

-- ===== 20261001000600_backfill_profiles.sql =====
-- Create profiles for any auth users that signed up before the profiles table
-- and its sign-up trigger existed. Safe to run more than once.
insert into public.profiles (id, full_name)
select u.id, nullif(u.raw_user_meta_data ->> 'full_name', '')
from auth.users u
on conflict (id) do nothing;

-- Ask the Supabase Data API to pick up the new tables immediately.
notify pgrst, 'reload schema';

-- ===== 20261001000700_simulation_modes.sql =====
-- "Practise this question again" (spec 2.8): a drill is a one-question
-- simulation that re-asks a question from an earlier session.
alter table public.simulations
  add column if not exists mode text not null default 'full',
  add column if not exists source_turn_id uuid references public.simulation_turns (id) on delete set null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'simulations_mode_check') then
    alter table public.simulations add constraint simulations_mode_check check (mode in ('full', 'drill'));
  end if;
end;
$$;

create index if not exists simulations_source_turn_id_idx on public.simulations (source_turn_id);

notify pgrst, 'reload schema';

-- ===== 20261001000800_billing.sql =====
-- Billing support (spec section 7).

-- Links a profile to its Paystack customer, so subscription events (which
-- carry only the customer) can be matched to the right account.
alter table public.profiles add column if not exists paystack_customer_code text;
create unique index if not exists profiles_paystack_customer_code_key
  on public.profiles (paystack_customer_code) where paystack_customer_code is not null;

-- What paid for each simulation, so plan allowances can be counted.
alter table public.simulations add column if not exists funded_by text;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'simulations_funded_by_check') then
    alter table public.simulations add constraint simulations_funded_by_check
      check (funded_by is null or funded_by in ('free', 'pro', 'credit'));
  end if;
end;
$$;

-- Atomic credit changes. Only the server (service role) may call these.
create or replace function public.add_credits(p_user_id uuid, p_amount integer)
returns integer
language sql
security definer
set search_path = ''
as $$
  update public.profiles
  set credits = credits + p_amount
  where id = p_user_id and p_amount > 0
  returning credits;
$$;

-- Spends one credit if the user has any. Returns the new balance, or null if none was available.
create or replace function public.consume_credit(p_user_id uuid)
returns integer
language sql
security definer
set search_path = ''
as $$
  update public.profiles
  set credits = credits - 1
  where id = p_user_id and credits > 0
  returning credits;
$$;

revoke all on function public.add_credits(uuid, integer) from public, anon, authenticated;
revoke all on function public.consume_credit(uuid) from public, anon, authenticated;
grant execute on function public.add_credits(uuid, integer) to service_role;
grant execute on function public.consume_credit(uuid) to service_role;

notify pgrst, 'reload schema';

-- ===== 20261001000900_staff_status_images.sql =====
-- Staff roles, account status and profile images.
--
-- Roles: founder (default), viewer (read-only admin), support (can also
-- suspend and reactivate), admin (everything). Permissions are enforced in
-- server code (lib/admin/permissions.ts); the database only stores the role.
--
-- Status: active, suspended (blocked until reactivated, data kept) or
-- terminated (permanently blocked, data kept, email can't be reused because
-- the auth user still exists). Sign-in is also blocked with a Supabase Auth
-- ban, set by server code.
--
-- Images: profile pictures and company logos live in the private `images`
-- bucket at `{owner_id}/...`. Only server code writes the paths, after
-- checking the file's content.
-- Idempotent: safe to run more than once.

------------------------------------------------------------------------------
-- profiles: roles, status, avatar
------------------------------------------------------------------------------
-- super_admin is added by a later migration; it is listed here too so that
-- re-running setup.sql on a database that already has a super admin works.
alter table public.profiles drop constraint if exists profiles_role_check;
-- Tidy role spelling first, so the check below never trips over "Admin" or
-- " admin". NOT VALID: existing rows aren't re-checked (so re-running
-- setup.sql can't fail on live data); every new or changed role is.
update public.profiles set role = lower(trim(role)) where role <> lower(trim(role));
alter table public.profiles
  add constraint profiles_role_check check (role in ('founder', 'viewer', 'support', 'admin', 'super_admin')) not valid;

alter table public.profiles add column if not exists status text not null default 'active';
alter table public.profiles drop constraint if exists profiles_status_check;
alter table public.profiles
  add constraint profiles_status_check check (status in ('active', 'suspended', 'terminated'));
alter table public.profiles add column if not exists status_reason text;
alter table public.profiles drop constraint if exists profiles_status_reason_check;
alter table public.profiles
  add constraint profiles_status_reason_check check (char_length(status_reason) <= 500);
alter table public.profiles add column if not exists status_changed_at timestamptz;
alter table public.profiles add column if not exists avatar_path text;

-- Founders still update only their name, country and onboarding flag.

------------------------------------------------------------------------------
-- startups: logo, written only by server code
------------------------------------------------------------------------------
alter table public.startups add column if not exists logo_path text;

-- Replace the table-wide insert/update grants with column lists that leave
-- out logo_path, so a founder can't point their logo at someone else's file.
revoke insert, update on public.startups from authenticated;
grant insert (
  owner_id, name, website, industry, country, stage, founding_year,
  business_model, revenue_monthly, revenue_currency, customers_count,
  growth_notes, raising, amount_seeking, seeking_currency, funding_type,
  previously_raised, use_of_funds
) on public.startups to authenticated;
grant update (
  name, website, industry, country, stage, founding_year,
  business_model, revenue_monthly, revenue_currency, customers_count,
  growth_notes, raising, amount_seeking, seeking_currency, funding_type,
  previously_raised, use_of_funds
) on public.startups to authenticated;

------------------------------------------------------------------------------
-- set_user_role: accept the new roles
------------------------------------------------------------------------------
create or replace function private.set_user_role(p_email text, p_role text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
begin
  if p_role not in ('founder', 'viewer', 'support', 'admin') then
    raise exception 'invalid role: %', p_role;
  end if;

  select u.id into v_user_id
  from auth.users u
  where lower(u.email) = lower(p_email);

  if v_user_id is null then
    raise exception 'no user with email %', p_email;
  end if;

  update public.profiles set role = p_role where id = v_user_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (null, 'profile.role_changed', 'profile', v_user_id, jsonb_build_object('role', p_role));

  return v_user_id;
end;
$$;

revoke all on function private.set_user_role(text, text) from public;

------------------------------------------------------------------------------
-- images bucket
------------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('images', 'images', false, 2097152, array['image/png', 'image/jpeg'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "images bucket: owner can read" on storage.objects;
create policy "images bucket: owner can read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- ===== 20261001001000_super_admin_notifications_showcase.sql =====
-- Super admin role, in-app notifications, landing-page showcase and the
-- report signature. Idempotent: safe to run more than once.

------------------------------------------------------------------------------
-- super_admin role (above admin)
------------------------------------------------------------------------------
alter table public.profiles drop constraint if exists profiles_role_check;
-- Tidy role spelling first, so the check below never trips over "Admin" or
-- " admin". NOT VALID: existing rows aren't re-checked (so re-running
-- setup.sql can't fail on live data); every new or changed role is.
update public.profiles set role = lower(trim(role)) where role <> lower(trim(role));
alter table public.profiles
  add constraint profiles_role_check check (role in ('founder', 'viewer', 'support', 'admin', 'super_admin')) not valid;

create or replace function private.set_user_role(p_email text, p_role text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
begin
  if p_role not in ('founder', 'viewer', 'support', 'admin', 'super_admin') then
    raise exception 'invalid role: %', p_role;
  end if;

  select u.id into v_user_id
  from auth.users u
  where lower(u.email) = lower(p_email);

  if v_user_id is null then
    raise exception 'no user with email %', p_email;
  end if;

  update public.profiles set role = p_role where id = v_user_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (null, 'profile.role_changed', 'profile', v_user_id, jsonb_build_object('role', p_role));

  return v_user_id;
end;
$$;

revoke all on function private.set_user_role(text, text) from public;

------------------------------------------------------------------------------
-- notifications: messages from staff to one founder or to everyone
------------------------------------------------------------------------------
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  -- null = sent to everyone
  user_id uuid references public.profiles (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 2000),
  -- optional link inside the app, e.g. /app/billing
  link text check (link is null or (link like '/%' and link not like '//%')),
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists notifications_user_id_idx on public.notifications (user_id, created_at desc);
create index if not exists notifications_created_at_idx on public.notifications (created_at desc);

create table if not exists public.notification_reads (
  notification_id uuid not null references public.notifications (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);
create index if not exists notification_reads_user_id_idx on public.notification_reads (user_id);

alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;
revoke all on public.notifications, public.notification_reads from anon, authenticated;
grant all on public.notifications, public.notification_reads to service_role;
grant select on public.notifications, public.notification_reads to authenticated;

drop policy if exists "notifications: recipients can read" on public.notifications;
create policy "notifications: recipients can read"
  on public.notifications for select to authenticated
  using (user_id is null or user_id = (select auth.uid()));

drop policy if exists "notification_reads: owner can read" on public.notification_reads;
create policy "notification_reads: owner can read"
  on public.notification_reads for select to authenticated
  using (user_id = (select auth.uid()));

drop trigger if exists set_updated_at on public.notifications;
create trigger set_updated_at before update on public.notifications
  for each row execute function private.set_updated_at();

------------------------------------------------------------------------------
-- showcase: startup logos, testimonials and partners on the public site
------------------------------------------------------------------------------
create table if not exists public.showcase_items (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('logo', 'testimonial', 'partner')),
  name text not null check (char_length(name) between 1 and 120),
  quote text check (char_length(quote) <= 600),
  person_name text check (char_length(person_name) <= 120),
  person_title text check (char_length(person_title) <= 120),
  url text check (url is null or url like 'https://%'),
  image_path text,
  -- staff confirm the company/person agreed to be shown
  permission_confirmed boolean not null default false,
  published boolean not null default false check (not published or permission_confirmed),
  position integer not null default 0,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists showcase_items_kind_idx on public.showcase_items (kind, position);

alter table public.showcase_items enable row level security;
revoke all on public.showcase_items from anon, authenticated;
grant all on public.showcase_items to service_role;
grant select on public.showcase_items to anon, authenticated;

drop policy if exists "showcase: anyone can read published items" on public.showcase_items;
create policy "showcase: anyone can read published items"
  on public.showcase_items for select to anon, authenticated
  using (published);

drop trigger if exists set_updated_at on public.showcase_items;
create trigger set_updated_at before update on public.showcase_items
  for each row execute function private.set_updated_at();

-- Public bucket: these images are shown on the public website.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('showcase', 'showcase', true, 2097152, array['image/png', 'image/jpeg'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

------------------------------------------------------------------------------
-- report signature: one row, server-only
------------------------------------------------------------------------------
create table if not exists public.report_signature (
  id integer primary key default 1 check (id = 1),
  signer_name text check (char_length(signer_name) <= 120),
  signer_title text check (char_length(signer_title) <= 120),
  signature_path text,
  enabled boolean not null default false,
  updated_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.report_signature enable row level security;
revoke all on public.report_signature from anon, authenticated;
grant all on public.report_signature to service_role;

drop trigger if exists set_updated_at on public.report_signature;
create trigger set_updated_at before update on public.report_signature
  for each row execute function private.set_updated_at();

-- ===== 20261001001100_activity_and_errors.sql =====
-- Sign-in history, daily activity and an error log for the admin area.
-- All three are written only by server code and kept for 90 days
-- (private.prune_activity). Idempotent: safe to run more than once.

------------------------------------------------------------------------------
-- profiles.last_seen_at
------------------------------------------------------------------------------
alter table public.profiles add column if not exists last_seen_at timestamptz;

------------------------------------------------------------------------------
-- sign_in_events: one row per sign-in attempt
------------------------------------------------------------------------------
create table if not exists public.sign_in_events (
  id uuid primary key default gen_random_uuid(),
  -- null for failed attempts on an unknown email
  user_id uuid references public.profiles (id) on delete cascade,
  -- sha-256 of the lower-cased email, so failed attempts can be counted per
  -- account without storing the address itself
  email_hash text not null,
  succeeded boolean not null,
  -- where they signed in: the founder login or the admin login
  surface text not null check (surface in ('app', 'admin')),
  failure_code text check (char_length(failure_code) <= 60),
  -- browser and device family only, e.g. "Chrome on Android"
  device text check (char_length(device) <= 80),
  created_at timestamptz not null default now()
);
create index if not exists sign_in_events_user_idx on public.sign_in_events (user_id, created_at desc);
create index if not exists sign_in_events_email_idx on public.sign_in_events (email_hash, created_at desc);
create index if not exists sign_in_events_created_idx on public.sign_in_events (created_at);

------------------------------------------------------------------------------
-- user_activity_days: which days each founder used the app
------------------------------------------------------------------------------
create table if not exists public.user_activity_days (
  user_id uuid not null references public.profiles (id) on delete cascade,
  day date not null,
  primary key (user_id, day)
);
create index if not exists user_activity_days_day_idx on public.user_activity_days (day);

------------------------------------------------------------------------------
-- app_errors: server and browser errors, for the admin Errors page
------------------------------------------------------------------------------
create table if not exists public.app_errors (
  id uuid primary key default gen_random_uuid(),
  source text not null check (source in ('server', 'browser')),
  -- the "Reference" shown to the user on the error page
  digest text check (char_length(digest) <= 100),
  message text not null check (char_length(message) <= 2000),
  path text check (char_length(path) <= 500),
  route_type text check (char_length(route_type) <= 40),
  user_id uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists app_errors_created_idx on public.app_errors (created_at desc);
create index if not exists app_errors_digest_idx on public.app_errors (digest);

------------------------------------------------------------------------------
-- Server-only: no browser access at all
------------------------------------------------------------------------------
alter table public.sign_in_events enable row level security;
alter table public.user_activity_days enable row level security;
alter table public.app_errors enable row level security;
revoke all on public.sign_in_events, public.user_activity_days, public.app_errors from anon, authenticated;
grant all on public.sign_in_events, public.user_activity_days, public.app_errors to service_role;

------------------------------------------------------------------------------
-- 90-day retention
------------------------------------------------------------------------------
create or replace function private.prune_activity()
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.sign_in_events where created_at < now() - interval '90 days';
  delete from public.user_activity_days where day < (now() - interval '90 days')::date;
  delete from public.app_errors where created_at < now() - interval '90 days';
$$;
revoke all on function private.prune_activity() from public;

-- Callable by the server (service role) through the API.
create or replace function public.prune_activity()
returns void
language sql
security definer
set search_path = ''
as $$ select private.prune_activity(); $$;
revoke all on function public.prune_activity() from public, anon, authenticated;
grant execute on function public.prune_activity() to service_role;

-- ===== 20261001001200_discounts_referrals_shares.sql =====
-- Discount codes, referrals, shareable report links and dollar payments.
-- Everything here is written by server code; founders can read only their
-- own share links. Idempotent: safe to run more than once.

------------------------------------------------------------------------------
-- payments: currency and discount details
------------------------------------------------------------------------------
-- amount_kobo holds the amount in the currency's smallest unit (kobo for NGN,
-- cents for USD), which is what Paystack uses.
alter table public.payments drop constraint if exists payments_currency_check;
alter table public.payments
  add constraint payments_currency_check check (currency in ('NGN', 'USD')) not valid;
alter table public.payments add column if not exists list_amount_kobo bigint check (list_amount_kobo >= 0);
alter table public.payments add column if not exists discount_code_id uuid;
alter table public.payments add column if not exists referral_discount boolean not null default false;

------------------------------------------------------------------------------
-- discount_codes: created by super admins
------------------------------------------------------------------------------
create table if not exists public.discount_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9][A-Z0-9_-]{2,31}$'),
  description text check (char_length(description) <= 200),
  percent_off integer not null check (percent_off between 1 and 100),
  -- which products it applies to
  products text[] not null default array['pro_monthly', 'credits_3', 'credits_10']
    check (products <@ array['pro_monthly', 'credits_3', 'credits_10'] and cardinality(products) > 0),
  max_redemptions integer check (max_redemptions > 0),
  expires_at timestamptz,
  active boolean not null default true,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.payments drop constraint if exists payments_discount_code_id_fkey;
alter table public.payments
  add constraint payments_discount_code_id_fkey foreign key (discount_code_id) references public.discount_codes (id) on delete set null;

-- One use per founder per code; recorded when the payment succeeds.
create table if not exists public.discount_redemptions (
  id uuid primary key default gen_random_uuid(),
  code_id uuid not null references public.discount_codes (id) on delete cascade,
  user_id uuid references public.profiles (id) on delete set null,
  payment_reference text,
  created_at timestamptz not null default now(),
  unique (code_id, user_id)
);
create index if not exists discount_redemptions_code_idx on public.discount_redemptions (code_id);

------------------------------------------------------------------------------
-- referrals
------------------------------------------------------------------------------
alter table public.profiles add column if not exists referral_code text;
alter table public.profiles drop constraint if exists profiles_referral_code_key;
alter table public.profiles add constraint profiles_referral_code_key unique (referral_code);
alter table public.profiles add column if not exists referred_by uuid;
alter table public.profiles drop constraint if exists profiles_referred_by_fkey;
alter table public.profiles
  add constraint profiles_referred_by_fkey foreign key (referred_by) references public.profiles (id) on delete set null;
alter table public.profiles drop constraint if exists profiles_not_self_referred;
alter table public.profiles add constraint profiles_not_self_referred check (referred_by is null or referred_by <> id);

-- One reward per referred founder, given on their first successful payment.
create table if not exists public.referral_rewards (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid references public.profiles (id) on delete set null,
  referred_id uuid references public.profiles (id) on delete set null,
  credits integer not null check (credits > 0),
  payment_reference text,
  created_at timestamptz not null default now()
);
create unique index if not exists referral_rewards_referred_idx on public.referral_rewards (referred_id);
create index if not exists referral_rewards_referrer_idx on public.referral_rewards (referrer_id);

------------------------------------------------------------------------------
-- report_shares: read-only links founders send to investors
------------------------------------------------------------------------------
create table if not exists public.report_shares (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports (id) on delete cascade,
  created_by uuid not null references public.profiles (id) on delete cascade,
  -- sha-256 of the secret in the link; the secret itself is never stored
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  views integer not null default 0,
  last_viewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists report_shares_report_idx on public.report_shares (report_id);

------------------------------------------------------------------------------
-- Access: server-only, except founders reading their own share links
------------------------------------------------------------------------------
alter table public.discount_codes enable row level security;
alter table public.discount_redemptions enable row level security;
alter table public.referral_rewards enable row level security;
alter table public.report_shares enable row level security;
revoke all on public.discount_codes, public.discount_redemptions, public.referral_rewards, public.report_shares
  from anon, authenticated;
grant all on public.discount_codes, public.discount_redemptions, public.referral_rewards, public.report_shares
  to service_role;
grant select on public.report_shares to authenticated;

drop policy if exists "report_shares: creator can read" on public.report_shares;
create policy "report_shares: creator can read"
  on public.report_shares for select to authenticated
  using (created_by = (select auth.uid()));

do $$
declare
  t text;
begin
  foreach t in array array['discount_codes', 'report_shares'] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format(
      'create trigger set_updated_at before update on public.%I
         for each row execute function private.set_updated_at()', t);
  end loop;
end;
$$;

-- ===== 20261001001300_referral_settings.sql =====
-- Referral programme settings, edited by super admins. One row, server-only.
-- Idempotent: safe to run more than once.

create table if not exists public.referral_settings (
  id integer primary key default 1 check (id = 1),
  enabled boolean not null default true,
  -- off the invited founder's first purchase
  friend_percent_off integer not null default 10 check (friend_percent_off between 0 and 100),
  -- simulation credits for the inviter when that founder first pays
  referrer_credits integer not null default 2 check (referrer_credits between 0 and 50),
  updated_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.referral_settings (id) values (1) on conflict (id) do nothing;

alter table public.referral_settings enable row level security;
revoke all on public.referral_settings from anon, authenticated;
grant all on public.referral_settings to service_role;

drop trigger if exists set_updated_at on public.referral_settings;
create trigger set_updated_at before update on public.referral_settings
  for each row execute function private.set_updated_at();

-- ===== 20261001001400_referral_minimum_spend.sql =====
-- Referral credits unlock only once the inviter has spent a minimum amount.
-- Credits earned before then are kept as "locked" and released automatically.
-- Idempotent: safe to run more than once.

alter table public.referral_settings
  add column if not exists min_spend_ngn bigint not null default 3750000 check (min_spend_ngn >= 0); -- kobo: ₦37,500
alter table public.referral_settings
  add column if not exists min_spend_usd bigint not null default 2500 check (min_spend_usd >= 0);    -- cents: $25

alter table public.referral_rewards add column if not exists status text not null default 'released';
alter table public.referral_rewards drop constraint if exists referral_rewards_status_check;
alter table public.referral_rewards
  add constraint referral_rewards_status_check check (status in ('locked', 'released'));
alter table public.referral_rewards add column if not exists released_at timestamptz;
create index if not exists referral_rewards_locked_idx on public.referral_rewards (referrer_id) where status = 'locked';

-- ===== 20261001001500_faq.sql =====
-- FAQ entries, edited by super admins, per language. English is the
-- fallback when a language has none. Public read for published entries.
-- Idempotent: safe to run more than once (seeded entries are added once and
-- never overwritten, so edits made in the admin area are kept).

create table if not exists public.faq_items (
  id uuid primary key default gen_random_uuid(),
  -- stable key for seeded entries, so re-running setup.sql doesn't duplicate them
  slug text check (slug ~ '^[a-z0-9-]{1,60}$'),
  locale text not null default 'en' check (locale in ('en', 'fr', 'pt', 'sw', 'ar', 'ha', 'yo', 'ig')),
  category text not null default 'General' check (char_length(category) between 1 and 60),
  question text not null check (char_length(question) between 1 and 300),
  answer text not null check (char_length(answer) between 1 and 4000),
  position integer not null default 0,
  published boolean not null default true,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (slug, locale)
);
create index if not exists faq_items_locale_idx on public.faq_items (locale, position);

alter table public.faq_items enable row level security;
revoke all on public.faq_items from anon, authenticated;
grant all on public.faq_items to service_role;
grant select on public.faq_items to anon, authenticated;

drop policy if exists "faq: anyone can read published entries" on public.faq_items;
create policy "faq: anyone can read published entries"
  on public.faq_items for select to anon, authenticated
  using (published);

drop trigger if exists set_updated_at on public.faq_items;
create trigger set_updated_at before update on public.faq_items
  for each row execute function private.set_updated_at();

insert into public.faq_items (slug, locale, category, question, answer, position, published) values
  ('what-is-raiseready', 'en', 'Getting started', 'What is RaiseReady?', 'RaiseReady helps African startup founders prepare for investor meetings. Upload your pitch deck, get a readiness assessment that shows what investors will look for, then practise with an AI investor who asks real questions, follows up on weak answers and points out where your answers don''t match your documents.', 0, true),
  ('who-is-it-for', 'en', 'Getting started', 'Who is RaiseReady for?', 'Founders preparing to raise money: from angels, seed VCs, accelerators or grant programmes. It is built for startups in Africa, with questions about local markets, currencies and regulation, not just a Silicon Valley checklist.', 10, true),
  ('what-do-i-need', 'en', 'Getting started', 'What do I need to get started?', 'An account and your pitch deck as a PDF. You can also add a financial model (Excel) and a business plan (Word or PDF) for a fuller picture. Files can be up to 20 MB, and decks up to 40 pages.', 20, true),
  ('how-score-works', 'en', 'Assessment and practice', 'How is my readiness score worked out?', 'We check what your documents say against what investors look for in 10 areas, such as problem, market, traction, team and financials. The AI only rates each checklist item; the score itself is calculated by fixed rules, so the same information always gives the same score and you can see exactly why it moved.', 30, true),
  ('investor-room', 'en', 'Assessment and practice', 'What happens in the Investor Room?', 'You choose who you''re pitching to (for example an angel investor or a seed VC) and how hard they should push. The AI investor then runs a meeting of about 10 to 20 questions in rounds, follows up when an answer is vague, and flags red flags such as contradictions with your own documents. At the end you get a score and feedback on every answer.', 40, true),
  ('is-it-advice', 'en', 'Assessment and practice', 'Is the feedback investment advice?', 'No. RaiseReady is a practice tool. Its assessments and feedback are AI-assisted and can be wrong. They are not investment, legal or financial advice, and a good score is not a promise of funding.', 50, true),
  ('practise-again', 'en', 'Assessment and practice', 'Can I practise a question again?', 'Yes. On your results you can retry any question as a short drill, so you can improve a weak answer without redoing the whole meeting.', 60, true),
  ('share-report', 'en', 'Assessment and practice', 'Can I share my report with investors?', 'Yes. On any report you can create a read-only link that works for 7, 30 or 90 days. Anyone with the link can read the report, including risks and red flags, so share it with care. You can turn a link off at any time and see how many times it was opened.', 70, true),
  ('free-plan', 'en', 'Pricing and payments', 'What does the free plan include?', 'One readiness assessment and one Investor Room session with an angel investor or seed VC, on friendly or analytical difficulty. No card is needed.', 80, true),
  ('pro-plan', 'en', 'Pricing and payments', 'What do I get with Pro?', 'Unlimited assessments, up to 30 practice sessions a month, every investor type and difficulty, downloadable PDF reports and progress tracking over time. Current prices are on the Pricing page.', 90, true),
  ('credits', 'en', 'Pricing and payments', 'How do simulation credits work?', 'Each credit pays for one Investor Room session with any investor and difficulty. Credits come in packs, are a one-off payment, and don''t need a subscription.', 100, true),
  ('how-to-pay', 'en', 'Pricing and payments', 'How do I pay?', 'Payments are handled by Paystack. You can pay with a Nigerian or foreign card. RaiseReady never sees or stores your card details.', 110, true),
  ('cancel-pro', 'en', 'Pricing and payments', 'Can I cancel Pro?', 'Yes, from the Billing page. You keep Pro until the end of the month you''ve paid for, then return to the free plan.', 120, true),
  ('discounts-invites', 'en', 'Pricing and payments', 'How do discount codes and invites work?', 'Enter a discount code on the Billing page to see the new price before you pay. Every founder also has an invite link on the Billing page: founders who join with it can get a discount on their first purchase, and you can earn free credits, which become usable once you''ve spent a minimum amount yourself. The current offer is shown on your Billing page.', 130, true),
  ('data-private', 'en', 'Your data', 'Who can see my documents?', 'Your documents are stored privately and shown only to you in the app. To analyse them, their content is sent to our AI provider. The privacy policy explains exactly what we store, who we share it with and for how long.', 140, true),
  ('delete-data', 'en', 'Your data', 'How do I delete my data?', 'You can delete individual documents on the Documents page, or your whole account under Settings. Deleting your account permanently removes your profile, startup, documents, assessments, practice sessions and reports, and cancels any Pro subscription.', 150, true),
  ('languages', 'en', 'Account and help', 'Can I use RaiseReady in my language?', 'Choose your language from the language menu at the top of the page. More of the app is being translated, and we''re working on practice sessions in more languages. Some pages, such as the legal pages, are only in English for now.', 160, true),
  ('something-wrong', 'en', 'Account and help', 'Something went wrong. What should I do?', 'Try again first. If it keeps happening, note the Reference shown on the error screen and send it to us, so we can see exactly what failed.', 170, true)
on conflict (slug, locale) do nothing;

-- ===== 20261001001600_pitch_decks.sql =====
-- Pitch deck builder: decks written by the AI from the founder's startup
-- profile and assessment, and the "deck_builder" one-off purchase.

-- The one-off product, alongside Pro and the credit packs.
alter table public.payments drop constraint if exists payments_product_check;
alter table public.payments
  add constraint payments_product_check
  check (product in ('pro_monthly', 'credits_3', 'credits_10', 'deck_builder')) not valid;

alter table public.discount_codes drop constraint if exists discount_codes_products_check;
alter table public.discount_codes
  add constraint discount_codes_products_check
  check (products <@ array['pro_monthly', 'credits_3', 'credits_10', 'deck_builder'] and cardinality(products) > 0) not valid;

-- Decks bought one at a time and not yet used. Written only by the server.
alter table public.profiles add column if not exists deck_credits integer not null default 0;
alter table public.profiles drop constraint if exists profiles_deck_credits_check;
alter table public.profiles add constraint profiles_deck_credits_check check (deck_credits >= 0);

create table if not exists public.pitch_decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  startup_id uuid not null references public.startups (id) on delete cascade,
  status text not null default 'generating' check (status in ('generating', 'ready', 'failed')),
  -- How the deck was paid for. 'preview' decks show only their first slides
  -- until unlocked with Pro or a deck purchase.
  access text not null check (access in ('preview', 'pro', 'credit')),
  title text,
  content jsonb,
  rewrites_used integer not null default 0 check (rewrites_used >= 0),
  -- When it was unlocked, so Pro's monthly allowance can be counted.
  unlocked_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists pitch_decks_startup_id_idx on public.pitch_decks (startup_id);
create index if not exists pitch_decks_user_id_idx on public.pitch_decks (user_id, unlocked_at);

drop trigger if exists set_updated_at on public.pitch_decks;
create trigger set_updated_at before update on public.pitch_decks
  for each row execute function private.set_updated_at();

alter table public.pitch_decks enable row level security;
revoke all on public.pitch_decks from anon, authenticated;
grant select on public.pitch_decks to authenticated;

drop policy if exists "pitch_decks: owner can read" on public.pitch_decks;
create policy "pitch_decks: owner can read"
  on public.pitch_decks for select to authenticated
  using ((select private.owns_startup(startup_id)));

-- Atomic deck credit changes. Only the server (service role) may call these.
create or replace function public.add_deck_credits(p_user_id uuid, p_amount integer)
returns integer
language sql
security definer
set search_path = ''
as $$
  update public.profiles
  set deck_credits = deck_credits + p_amount
  where id = p_user_id and p_amount > 0
  returning deck_credits;
$$;

-- Spends one deck credit if the user has any. Returns the new balance, or null if none was available.
create or replace function public.consume_deck_credit(p_user_id uuid)
returns integer
language sql
security definer
set search_path = ''
as $$
  update public.profiles
  set deck_credits = deck_credits - 1
  where id = p_user_id and deck_credits > 0
  returning deck_credits;
$$;

revoke all on function public.add_deck_credits(uuid, integer) from public, anon, authenticated;
revoke all on function public.consume_deck_credit(uuid) from public, anon, authenticated;
grant execute on function public.add_deck_credits(uuid, integer) to service_role;
grant execute on function public.consume_deck_credit(uuid) to service_role;

notify pgrst, 'reload schema';

-- ===== Check =====
select
  (select count(*) from pg_tables where schemaname = 'public') as tables_created,
  (select count(*) from public.profiles) as profiles,
  (select count(*) from storage.buckets where id in ('documents', 'reports')) as buckets,
  case
    when (select count(*) from pg_tables where schemaname = 'public') >= 13
     and (select count(*) from storage.buckets where id in ('documents', 'reports')) = 2
    then 'SETUP COMPLETE'
    else 'SETUP INCOMPLETE - send this to Claude'
  end as result;
