-- RaiseReady database setup. Paste ALL of this into the Supabase SQL Editor and click Run.
-- Generated by scripts/build-setup-sql.sh from supabase/migrations. Safe to run more than once.

-- ===== 20261001000100_helpers.sql =====
-- Shared helpers used by every table.

create extension if not exists pgcrypto with schema extensions;

-- Functions that RLS policies call live in a schema that is not exposed
-- through the PostgREST API.
create schema if not exists private;
grant usage on schema private to authenticated, service_role;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ===== 20261001000200_schema.sql =====
-- Core RaiseReady schema (spec section 5).
-- Enumerations are text + check constraints so they can be extended by later
-- migrations without enum-type rewrites.

------------------------------------------------------------------------------
-- profiles: one row per auth user, created automatically on sign-up.
------------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  country text,
  role text not null default 'founder' check (role in ('founder', 'admin')),
  plan text not null default 'free' check (plan in ('free', 'pro')),
  credits integer not null default 0 check (credits >= 0),
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

------------------------------------------------------------------------------
-- startups
------------------------------------------------------------------------------
create table if not exists public.startups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 200),
  website text,
  industry text,
  country text,
  stage text check (stage in ('idea', 'pre_seed', 'seed', 'series_a', 'other')),
  founding_year integer check (founding_year between 1900 and 2100),
  business_model text,
  revenue_monthly numeric(18, 2) check (revenue_monthly >= 0),
  revenue_currency char(3) not null default 'NGN',
  customers_count integer check (customers_count >= 0),
  growth_notes text,
  raising boolean not null default false,
  amount_seeking numeric(18, 2) check (amount_seeking >= 0),
  seeking_currency char(3) not null default 'NGN',
  funding_type text check (funding_type in ('equity', 'safe', 'convertible_note', 'grant', 'debt', 'other')),
  previously_raised boolean,
  use_of_funds text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists startups_owner_id_idx on public.startups (owner_id);

------------------------------------------------------------------------------
-- documents
------------------------------------------------------------------------------
create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  kind text not null check (kind in ('pitch_deck', 'financial_model', 'business_plan', 'other')),
  original_filename text,
  storage_path text not null unique,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 20 * 1024 * 1024),
  status text not null default 'uploaded' check (status in ('uploaded', 'processing', 'ready', 'failed')),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists documents_startup_id_idx on public.documents (startup_id);

------------------------------------------------------------------------------
-- knowledge_profiles: versioned structured extraction (spec 6.1)
------------------------------------------------------------------------------
create table if not exists public.knowledge_profiles (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  version integer not null check (version > 0),
  data jsonb not null,
  source_document_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (startup_id, version)
);

------------------------------------------------------------------------------
-- assessments (spec 6.2)
------------------------------------------------------------------------------
create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  knowledge_profile_id uuid references public.knowledge_profiles (id) on delete set null,
  overall_score integer not null check (overall_score between 0 and 100),
  band text not null check (band in ('not_ready', 'getting_there', 'nearly_ready', 'investor_ready')),
  dimension_scores jsonb not null,
  strengths jsonb not null default '[]',
  weaknesses jsonb not null default '[]',
  recommended_actions jsonb not null default '[]',
  rubric_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists assessments_startup_id_created_at_idx on public.assessments (startup_id, created_at desc);
create index if not exists assessments_knowledge_profile_id_idx on public.assessments (knowledge_profile_id);

------------------------------------------------------------------------------
-- simulations (spec 6.3)
------------------------------------------------------------------------------
create table if not exists public.simulations (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  persona text not null check (persona in ('seed_vc', 'angel', 'grant_evaluator')),
  difficulty text not null check (difficulty in ('friendly', 'analytical', 'tough')),
  funding_type text,
  status text not null default 'active' check (status in ('active', 'completed', 'abandoned')),
  current_round integer not null default 1 check (current_round between 1 and 10),
  overall_score integer check (overall_score between 0 and 100),
  investor_confidence text check (investor_confidence in ('low', 'medium', 'high')),
  final_evaluation jsonb,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists simulations_startup_id_created_at_idx on public.simulations (startup_id, created_at desc);

create table if not exists public.simulation_turns (
  id uuid primary key default gen_random_uuid(),
  simulation_id uuid not null references public.simulations (id) on delete cascade,
  turn_index integer not null check (turn_index >= 0),
  round integer not null check (round between 1 and 10),
  role text not null check (role in ('investor', 'founder', 'system')),
  content text not null,
  evaluation jsonb,
  red_flags jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (simulation_id, turn_index)
);

create table if not exists public.red_flags (
  id uuid primary key default gen_random_uuid(),
  simulation_id uuid not null references public.simulations (id) on delete cascade,
  turn_id uuid references public.simulation_turns (id) on delete cascade,
  type text not null check (type in ('contradiction', 'unsupported_claim', 'weak_answer', 'missing_info')),
  severity text not null check (severity in ('low', 'medium', 'high')),
  description text not null,
  evidence jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists red_flags_simulation_id_idx on public.red_flags (simulation_id);
create index if not exists red_flags_turn_id_idx on public.red_flags (turn_id);

------------------------------------------------------------------------------
-- reports (spec 6.4)
------------------------------------------------------------------------------
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  assessment_id uuid references public.assessments (id) on delete set null,
  simulation_id uuid references public.simulations (id) on delete set null,
  content jsonb not null,
  pdf_storage_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists reports_startup_id_idx on public.reports (startup_id);
create index if not exists reports_assessment_id_idx on public.reports (assessment_id);
create index if not exists reports_simulation_id_idx on public.reports (simulation_id);

------------------------------------------------------------------------------
-- payments & subscriptions (spec 7). Written only by the server.
------------------------------------------------------------------------------
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  provider text not null default 'paystack' check (provider in ('paystack')),
  reference text not null unique,
  amount_kobo bigint not null check (amount_kobo >= 0),
  currency char(3) not null default 'NGN',
  product text not null check (product in ('pro_monthly', 'credits_3', 'credits_10')),
  status text not null default 'pending' check (status in ('pending', 'success', 'failed', 'abandoned', 'reversed')),
  raw_event jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists payments_user_id_idx on public.payments (user_id);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  provider_subscription_code text unique,
  status text not null check (status in ('active', 'non_renewing', 'attention', 'cancelled', 'completed')),
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists subscriptions_user_id_idx on public.subscriptions (user_id);

------------------------------------------------------------------------------
-- ai_calls: cost tracking. user_id is nulled on account deletion so aggregate
-- cost history survives without being linked to a person. No founder content
-- is stored here.
------------------------------------------------------------------------------
create table if not exists public.ai_calls (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles (id) on delete set null,
  purpose text not null,
  model text not null,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  latency_ms integer check (latency_ms >= 0),
  success boolean not null,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ai_calls_user_id_created_at_idx on public.ai_calls (user_id, created_at desc);
create index if not exists ai_calls_created_at_idx on public.ai_calls (created_at desc);

------------------------------------------------------------------------------
-- audit_logs: survives actor deletion (actor_id is nulled).
------------------------------------------------------------------------------
create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles (id) on delete set null,
  action text not null,
  target_type text,
  target_id uuid,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists audit_logs_actor_id_idx on public.audit_logs (actor_id);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);

------------------------------------------------------------------------------
-- updated_at triggers on every table
------------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'startups', 'documents', 'knowledge_profiles', 'assessments',
    'simulations', 'simulation_turns', 'red_flags', 'reports', 'payments',
    'subscriptions', 'ai_calls', 'audit_logs'
  ] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format(
      'create trigger set_updated_at before update on public.%I
         for each row execute function private.set_updated_at()', t);
  end loop;
end;
$$;

------------------------------------------------------------------------------
-- Create a profile automatically when an auth user signs up.
------------------------------------------------------------------------------
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, nullif(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

-- ===== 20261001000300_rls.sql =====
-- Row Level Security (spec section 8).
--
-- Access model:
--   * Founders (role `authenticated`) can only see rows they own.
--   * Founders may directly write only what they author: their profile's
--     editable fields, their startups, and their document records.
--   * Everything derived by the app (extractions, scores, simulations,
--     reports), all billing state, AI usage and audit logs are written only by
--     server code using the service role, which bypasses RLS.
--   * Admin views read through the service role on the server; there are no
--     admin RLS policies, so an `admin` profile gets no extra access from the
--     browser.
--   * `anon` has no table access at all.

------------------------------------------------------------------------------
-- Ownership helpers. SECURITY DEFINER so policies on child tables do not
-- recurse through the startups policy; each checks auth.uid() explicitly.
------------------------------------------------------------------------------
create or replace function private.owns_startup(p_startup_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.startups s
    where s.id = p_startup_id and s.owner_id = (select auth.uid())
  );
$$;

create or replace function private.owns_simulation(p_simulation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.simulations sim
    join public.startups s on s.id = sim.startup_id
    where sim.id = p_simulation_id and s.owner_id = (select auth.uid())
  );
$$;

revoke all on function private.owns_startup(uuid) from public;
revoke all on function private.owns_simulation(uuid) from public;
grant execute on function private.owns_startup(uuid) to authenticated;
grant execute on function private.owns_simulation(uuid) to authenticated;
revoke all on function private.set_updated_at() from public;
revoke all on function private.handle_new_user() from public;

------------------------------------------------------------------------------
-- Enable RLS everywhere and reset privileges to least privilege.
------------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'startups', 'documents', 'knowledge_profiles', 'assessments',
    'simulations', 'simulation_turns', 'red_flags', 'reports', 'payments',
    'subscriptions', 'ai_calls', 'audit_logs'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant all on public.%I to service_role', t);
  end loop;
end;
$$;

------------------------------------------------------------------------------
-- profiles: read own; update only non-privileged columns.
-- role, plan and credits can never be changed from the browser.
------------------------------------------------------------------------------
grant select on public.profiles to authenticated;
grant update (full_name, country, onboarding_complete) on public.profiles to authenticated;

drop policy if exists "profiles: owner can read" on public.profiles;
create policy "profiles: owner can read"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()));

drop policy if exists "profiles: owner can update" on public.profiles;
create policy "profiles: owner can update"
  on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

------------------------------------------------------------------------------
-- startups: full CRUD on own rows.
------------------------------------------------------------------------------
grant select, insert, update, delete on public.startups to authenticated;

drop policy if exists "startups: owner can read" on public.startups;
create policy "startups: owner can read"
  on public.startups for select to authenticated
  using (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can insert" on public.startups;
create policy "startups: owner can insert"
  on public.startups for insert to authenticated
  with check (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can update" on public.startups;
create policy "startups: owner can update"
  on public.startups for update to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can delete" on public.startups;
create policy "startups: owner can delete"
  on public.startups for delete to authenticated
  using (owner_id = (select auth.uid()));

------------------------------------------------------------------------------
-- documents: read and delete own. Inserts and status updates happen on the
-- server after the file's content type has been validated.
------------------------------------------------------------------------------
grant select, delete on public.documents to authenticated;

drop policy if exists "documents: owner can read" on public.documents;
create policy "documents: owner can read"
  on public.documents for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "documents: owner can delete" on public.documents;
create policy "documents: owner can delete"
  on public.documents for delete to authenticated
  using ((select private.owns_startup(startup_id)));

------------------------------------------------------------------------------
-- Derived, startup-scoped data: read-only for the owner.
------------------------------------------------------------------------------
grant select on public.knowledge_profiles, public.assessments,
  public.simulations, public.reports to authenticated;

drop policy if exists "knowledge_profiles: owner can read" on public.knowledge_profiles;
create policy "knowledge_profiles: owner can read"
  on public.knowledge_profiles for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "assessments: owner can read" on public.assessments;
create policy "assessments: owner can read"
  on public.assessments for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "simulations: owner can read" on public.simulations;
create policy "simulations: owner can read"
  on public.simulations for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "reports: owner can read" on public.reports;
create policy "reports: owner can read"
  on public.reports for select to authenticated
  using ((select private.owns_startup(startup_id)));

grant select on public.simulation_turns, public.red_flags to authenticated;

drop policy if exists "simulation_turns: owner can read" on public.simulation_turns;
create policy "simulation_turns: owner can read"
  on public.simulation_turns for select to authenticated
  using ((select private.owns_simulation(simulation_id)));

drop policy if exists "red_flags: owner can read" on public.red_flags;
create policy "red_flags: owner can read"
  on public.red_flags for select to authenticated
  using ((select private.owns_simulation(simulation_id)));

------------------------------------------------------------------------------
-- Billing: read own history; written only by the server (Paystack webhook).
------------------------------------------------------------------------------
grant select on public.payments, public.subscriptions to authenticated;

drop policy if exists "payments: owner can read" on public.payments;
create policy "payments: owner can read"
  on public.payments for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "subscriptions: owner can read" on public.subscriptions;
create policy "subscriptions: owner can read"
  on public.subscriptions for select to authenticated
  using (user_id = (select auth.uid()));

-- ai_calls and audit_logs: no policies => no access except service role.

-- ===== 20261001000400_storage.sql =====
-- Private storage buckets (spec sections 3, 6.5, 8).
-- Object paths are `{owner_id}/{startup_id}/{file}` so ownership can be
-- checked from the first path segment.
-- Uploads and deletes go through server code (service role) after content
-- validation; founders may only read their own objects, which is what creating
-- a short-lived signed URL with their session requires.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('documents', 'documents', false, 20971520, array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]),
  ('reports', 'reports', false, 20971520, array['application/pdf'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "documents bucket: owner can read" on storage.objects;
create policy "documents bucket: owner can read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "reports bucket: owner can read" on storage.objects;
create policy "reports bucket: owner can read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'reports'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- ===== 20261001000500_admin.sql =====
-- Admin role seeding. Admin access is enforced server-side by checking
-- profiles.role; this function is the supported way to grant it.
-- Run from the Supabase SQL editor (as postgres):
--   select private.set_user_role('you@example.com', 'admin');
-- or with `npm run db:seed-admin -- you@example.com`.

create or replace function private.set_user_role(p_email text, p_role text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
begin
  if p_role not in ('founder', 'admin') then
    raise exception 'invalid role: %', p_role;
  end if;

  select u.id into v_user_id
  from auth.users u
  where lower(u.email) = lower(p_email);

  if v_user_id is null then
    raise exception 'no user with email %', p_email;
  end if;

  update public.profiles set role = p_role where id = v_user_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (null, 'profile.role_changed', 'profile', v_user_id, jsonb_build_object('role', p_role));

  return v_user_id;
end;
$$;

revoke all on function private.set_user_role(text, text) from public;

-- ===== 20261001000600_backfill_profiles.sql =====
-- Create profiles for any auth users that signed up before the profiles table
-- and its sign-up trigger existed. Safe to run more than once.
insert into public.profiles (id, full_name)
select u.id, nullif(u.raw_user_meta_data ->> 'full_name', '')
from auth.users u
on conflict (id) do nothing;

-- Ask the Supabase Data API to pick up the new tables immediately.
notify pgrst, 'reload schema';

-- ===== 20261001000700_simulation_modes.sql =====
-- "Practise this question again" (spec 2.8): a drill is a one-question
-- simulation that re-asks a question from an earlier session.
alter table public.simulations
  add column if not exists mode text not null default 'full',
  add column if not exists source_turn_id uuid references public.simulation_turns (id) on delete set null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'simulations_mode_check') then
    alter table public.simulations add constraint simulations_mode_check check (mode in ('full', 'drill'));
  end if;
end;
$$;

create index if not exists simulations_source_turn_id_idx on public.simulations (source_turn_id);

notify pgrst, 'reload schema';

-- ===== 20261001000800_billing.sql =====
-- Billing support (spec section 7).

-- Links a profile to its Paystack customer, so subscription events (which
-- carry only the customer) can be matched to the right account.
alter table public.profiles add column if not exists paystack_customer_code text;
create unique index if not exists profiles_paystack_customer_code_key
  on public.profiles (paystack_customer_code) where paystack_customer_code is not null;

-- What paid for each simulation, so plan allowances can be counted.
alter table public.simulations add column if not exists funded_by text;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'simulations_funded_by_check') then
    alter table public.simulations add constraint simulations_funded_by_check
      check (funded_by is null or funded_by in ('free', 'pro', 'credit'));
  end if;
end;
$$;

-- Atomic credit changes. Only the server (service role) may call these.
create or replace function public.add_credits(p_user_id uuid, p_amount integer)
returns integer
language sql
security definer
set search_path = ''
as $$
  update public.profiles
  set credits = credits + p_amount
  where id = p_user_id and p_amount > 0
  returning credits;
$$;

-- Spends one credit if the user has any. Returns the new balance, or null if none was available.
create or replace function public.consume_credit(p_user_id uuid)
returns integer
language sql
security definer
set search_path = ''
as $$
  update public.profiles
  set credits = credits - 1
  where id = p_user_id and credits > 0
  returning credits;
$$;

revoke all on function public.add_credits(uuid, integer) from public, anon, authenticated;
revoke all on function public.consume_credit(uuid) from public, anon, authenticated;
grant execute on function public.add_credits(uuid, integer) to service_role;
grant execute on function public.consume_credit(uuid) to service_role;

notify pgrst, 'reload schema';

-- ===== 20261001000900_staff_status_images.sql =====
-- Staff roles, account status and profile images.
--
-- Roles: founder (default), viewer (read-only admin), support (can also
-- suspend and reactivate), admin (everything). Permissions are enforced in
-- server code (lib/admin/permissions.ts); the database only stores the role.
--
-- Status: active, suspended (blocked until reactivated, data kept) or
-- terminated (permanently blocked, data kept, email can't be reused because
-- the auth user still exists). Sign-in is also blocked with a Supabase Auth
-- ban, set by server code.
--
-- Images: profile pictures and company logos live in the private `images`
-- bucket at `{owner_id}/...`. Only server code writes the paths, after
-- checking the file's content.
-- Idempotent: safe to run more than once.

------------------------------------------------------------------------------
-- profiles: roles, status, avatar
------------------------------------------------------------------------------
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check check (role in ('founder', 'viewer', 'support', 'admin'));

alter table public.profiles add column if not exists status text not null default 'active';
alter table public.profiles drop constraint if exists profiles_status_check;
alter table public.profiles
  add constraint profiles_status_check check (status in ('active', 'suspended', 'terminated'));
alter table public.profiles add column if not exists status_reason text;
alter table public.profiles drop constraint if exists profiles_status_reason_check;
alter table public.profiles
  add constraint profiles_status_reason_check check (char_length(status_reason) <= 500);
alter table public.profiles add column if not exists status_changed_at timestamptz;
alter table public.profiles add column if not exists avatar_path text;

-- Founders still update only their name, country and onboarding flag.

------------------------------------------------------------------------------
-- startups: logo, written only by server code
------------------------------------------------------------------------------
alter table public.startups add column if not exists logo_path text;

-- Replace the table-wide insert/update grants with column lists that leave
-- out logo_path, so a founder can't point their logo at someone else's file.
revoke insert, update on public.startups from authenticated;
grant insert (
  owner_id, name, website, industry, country, stage, founding_year,
  business_model, revenue_monthly, revenue_currency, customers_count,
  growth_notes, raising, amount_seeking, seeking_currency, funding_type,
  previously_raised, use_of_funds
) on public.startups to authenticated;
grant update (
  name, website, industry, country, stage, founding_year,
  business_model, revenue_monthly, revenue_currency, customers_count,
  growth_notes, raising, amount_seeking, seeking_currency, funding_type,
  previously_raised, use_of_funds
) on public.startups to authenticated;

------------------------------------------------------------------------------
-- set_user_role: accept the new roles
------------------------------------------------------------------------------
create or replace function private.set_user_role(p_email text, p_role text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
begin
  if p_role not in ('founder', 'viewer', 'support', 'admin') then
    raise exception 'invalid role: %', p_role;
  end if;

  select u.id into v_user_id
  from auth.users u
  where lower(u.email) = lower(p_email);

  if v_user_id is null then
    raise exception 'no user with email %', p_email;
  end if;

  update public.profiles set role = p_role where id = v_user_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (null, 'profile.role_changed', 'profile', v_user_id, jsonb_build_object('role', p_role));

  return v_user_id;
end;
$$;

revoke all on function private.set_user_role(text, text) from public;

------------------------------------------------------------------------------
-- images bucket
------------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('images', 'images', false, 2097152, array['image/png', 'image/jpeg'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "images bucket: owner can read" on storage.objects;
create policy "images bucket: owner can read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'images'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- ===== 20261001001000_super_admin_notifications_showcase.sql =====
-- Super admin role, in-app notifications, landing-page showcase and the
-- report signature. Idempotent: safe to run more than once.

------------------------------------------------------------------------------
-- super_admin role (above admin)
------------------------------------------------------------------------------
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check check (role in ('founder', 'viewer', 'support', 'admin', 'super_admin'));

create or replace function private.set_user_role(p_email text, p_role text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
begin
  if p_role not in ('founder', 'viewer', 'support', 'admin', 'super_admin') then
    raise exception 'invalid role: %', p_role;
  end if;

  select u.id into v_user_id
  from auth.users u
  where lower(u.email) = lower(p_email);

  if v_user_id is null then
    raise exception 'no user with email %', p_email;
  end if;

  update public.profiles set role = p_role where id = v_user_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (null, 'profile.role_changed', 'profile', v_user_id, jsonb_build_object('role', p_role));

  return v_user_id;
end;
$$;

revoke all on function private.set_user_role(text, text) from public;

------------------------------------------------------------------------------
-- notifications: messages from staff to one founder or to everyone
------------------------------------------------------------------------------
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  -- null = sent to everyone
  user_id uuid references public.profiles (id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 2000),
  -- optional link inside the app, e.g. /app/billing
  link text check (link is null or (link like '/%' and link not like '//%')),
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists notifications_user_id_idx on public.notifications (user_id, created_at desc);
create index if not exists notifications_created_at_idx on public.notifications (created_at desc);

create table if not exists public.notification_reads (
  notification_id uuid not null references public.notifications (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);
create index if not exists notification_reads_user_id_idx on public.notification_reads (user_id);

alter table public.notifications enable row level security;
alter table public.notification_reads enable row level security;
revoke all on public.notifications, public.notification_reads from anon, authenticated;
grant all on public.notifications, public.notification_reads to service_role;
grant select on public.notifications, public.notification_reads to authenticated;

drop policy if exists "notifications: recipients can read" on public.notifications;
create policy "notifications: recipients can read"
  on public.notifications for select to authenticated
  using (user_id is null or user_id = (select auth.uid()));

drop policy if exists "notification_reads: owner can read" on public.notification_reads;
create policy "notification_reads: owner can read"
  on public.notification_reads for select to authenticated
  using (user_id = (select auth.uid()));

drop trigger if exists set_updated_at on public.notifications;
create trigger set_updated_at before update on public.notifications
  for each row execute function private.set_updated_at();

------------------------------------------------------------------------------
-- showcase: startup logos, testimonials and partners on the public site
------------------------------------------------------------------------------
create table if not exists public.showcase_items (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('logo', 'testimonial', 'partner')),
  name text not null check (char_length(name) between 1 and 120),
  quote text check (char_length(quote) <= 600),
  person_name text check (char_length(person_name) <= 120),
  person_title text check (char_length(person_title) <= 120),
  url text check (url is null or url like 'https://%'),
  image_path text,
  -- staff confirm the company/person agreed to be shown
  permission_confirmed boolean not null default false,
  published boolean not null default false check (not published or permission_confirmed),
  position integer not null default 0,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists showcase_items_kind_idx on public.showcase_items (kind, position);

alter table public.showcase_items enable row level security;
revoke all on public.showcase_items from anon, authenticated;
grant all on public.showcase_items to service_role;
grant select on public.showcase_items to anon, authenticated;

drop policy if exists "showcase: anyone can read published items" on public.showcase_items;
create policy "showcase: anyone can read published items"
  on public.showcase_items for select to anon, authenticated
  using (published);

drop trigger if exists set_updated_at on public.showcase_items;
create trigger set_updated_at before update on public.showcase_items
  for each row execute function private.set_updated_at();

-- Public bucket: these images are shown on the public website.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('showcase', 'showcase', true, 2097152, array['image/png', 'image/jpeg'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

------------------------------------------------------------------------------
-- report signature: one row, server-only
------------------------------------------------------------------------------
create table if not exists public.report_signature (
  id integer primary key default 1 check (id = 1),
  signer_name text check (char_length(signer_name) <= 120),
  signer_title text check (char_length(signer_title) <= 120),
  signature_path text,
  enabled boolean not null default false,
  updated_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.report_signature enable row level security;
revoke all on public.report_signature from anon, authenticated;
grant all on public.report_signature to service_role;

drop trigger if exists set_updated_at on public.report_signature;
create trigger set_updated_at before update on public.report_signature
  for each row execute function private.set_updated_at();

-- ===== 20261001001100_activity_and_errors.sql =====
-- Sign-in history, daily activity and an error log for the admin area.
-- All three are written only by server code and kept for 90 days
-- (private.prune_activity). Idempotent: safe to run more than once.

------------------------------------------------------------------------------
-- profiles.last_seen_at
------------------------------------------------------------------------------
alter table public.profiles add column if not exists last_seen_at timestamptz;

------------------------------------------------------------------------------
-- sign_in_events: one row per sign-in attempt
------------------------------------------------------------------------------
create table if not exists public.sign_in_events (
  id uuid primary key default gen_random_uuid(),
  -- null for failed attempts on an unknown email
  user_id uuid references public.profiles (id) on delete cascade,
  -- sha-256 of the lower-cased email, so failed attempts can be counted per
  -- account without storing the address itself
  email_hash text not null,
  succeeded boolean not null,
  -- where they signed in: the founder login or the admin login
  surface text not null check (surface in ('app', 'admin')),
  failure_code text check (char_length(failure_code) <= 60),
  -- browser and device family only, e.g. "Chrome on Android"
  device text check (char_length(device) <= 80),
  created_at timestamptz not null default now()
);
create index if not exists sign_in_events_user_idx on public.sign_in_events (user_id, created_at desc);
create index if not exists sign_in_events_email_idx on public.sign_in_events (email_hash, created_at desc);
create index if not exists sign_in_events_created_idx on public.sign_in_events (created_at);

------------------------------------------------------------------------------
-- user_activity_days: which days each founder used the app
------------------------------------------------------------------------------
create table if not exists public.user_activity_days (
  user_id uuid not null references public.profiles (id) on delete cascade,
  day date not null,
  primary key (user_id, day)
);
create index if not exists user_activity_days_day_idx on public.user_activity_days (day);

------------------------------------------------------------------------------
-- app_errors: server and browser errors, for the admin Errors page
------------------------------------------------------------------------------
create table if not exists public.app_errors (
  id uuid primary key default gen_random_uuid(),
  source text not null check (source in ('server', 'browser')),
  -- the "Reference" shown to the user on the error page
  digest text check (char_length(digest) <= 100),
  message text not null check (char_length(message) <= 2000),
  path text check (char_length(path) <= 500),
  route_type text check (char_length(route_type) <= 40),
  user_id uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists app_errors_created_idx on public.app_errors (created_at desc);
create index if not exists app_errors_digest_idx on public.app_errors (digest);

------------------------------------------------------------------------------
-- Server-only: no browser access at all
------------------------------------------------------------------------------
alter table public.sign_in_events enable row level security;
alter table public.user_activity_days enable row level security;
alter table public.app_errors enable row level security;
revoke all on public.sign_in_events, public.user_activity_days, public.app_errors from anon, authenticated;
grant all on public.sign_in_events, public.user_activity_days, public.app_errors to service_role;

------------------------------------------------------------------------------
-- 90-day retention
------------------------------------------------------------------------------
create or replace function private.prune_activity()
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.sign_in_events where created_at < now() - interval '90 days';
  delete from public.user_activity_days where day < (now() - interval '90 days')::date;
  delete from public.app_errors where created_at < now() - interval '90 days';
$$;
revoke all on function private.prune_activity() from public;

-- Callable by the server (service role) through the API.
create or replace function public.prune_activity()
returns void
language sql
security definer
set search_path = ''
as $$ select private.prune_activity(); $$;
revoke all on function public.prune_activity() from public, anon, authenticated;
grant execute on function public.prune_activity() to service_role;

-- ===== Check =====
select
  (select count(*) from pg_tables where schemaname = 'public') as tables_created,
  (select count(*) from public.profiles) as profiles,
  (select count(*) from storage.buckets where id in ('documents', 'reports')) as buckets,
  case
    when (select count(*) from pg_tables where schemaname = 'public') >= 13
     and (select count(*) from storage.buckets where id in ('documents', 'reports')) = 2
    then 'SETUP COMPLETE'
    else 'SETUP INCOMPLETE - send this to Claude'
  end as result;
