-- RaiseReady database setup. Paste ALL of this into the Supabase SQL Editor and click Run.
-- Generated by scripts/build-setup-sql.sh from supabase/migrations. Safe to run more than once.

-- ===== 20261001000100_helpers.sql =====
-- Shared helpers used by every table.

create extension if not exists pgcrypto with schema extensions;

-- Functions that RLS policies call live in a schema that is not exposed
-- through the PostgREST API.
create schema if not exists private;
grant usage on schema private to authenticated, service_role;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ===== 20261001000200_schema.sql =====
-- Core RaiseReady schema (spec section 5).
-- Enumerations are text + check constraints so they can be extended by later
-- migrations without enum-type rewrites.

------------------------------------------------------------------------------
-- profiles: one row per auth user, created automatically on sign-up.
------------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text,
  country text,
  role text not null default 'founder' check (role in ('founder', 'admin')),
  plan text not null default 'free' check (plan in ('free', 'pro')),
  credits integer not null default 0 check (credits >= 0),
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

------------------------------------------------------------------------------
-- startups
------------------------------------------------------------------------------
create table if not exists public.startups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 200),
  website text,
  industry text,
  country text,
  stage text check (stage in ('idea', 'pre_seed', 'seed', 'series_a', 'other')),
  founding_year integer check (founding_year between 1900 and 2100),
  business_model text,
  revenue_monthly numeric(18, 2) check (revenue_monthly >= 0),
  revenue_currency char(3) not null default 'NGN',
  customers_count integer check (customers_count >= 0),
  growth_notes text,
  raising boolean not null default false,
  amount_seeking numeric(18, 2) check (amount_seeking >= 0),
  seeking_currency char(3) not null default 'NGN',
  funding_type text check (funding_type in ('equity', 'safe', 'convertible_note', 'grant', 'debt', 'other')),
  previously_raised boolean,
  use_of_funds text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists startups_owner_id_idx on public.startups (owner_id);

------------------------------------------------------------------------------
-- documents
------------------------------------------------------------------------------
create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  kind text not null check (kind in ('pitch_deck', 'financial_model', 'business_plan', 'other')),
  original_filename text,
  storage_path text not null unique,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 20 * 1024 * 1024),
  status text not null default 'uploaded' check (status in ('uploaded', 'processing', 'ready', 'failed')),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists documents_startup_id_idx on public.documents (startup_id);

------------------------------------------------------------------------------
-- knowledge_profiles: versioned structured extraction (spec 6.1)
------------------------------------------------------------------------------
create table if not exists public.knowledge_profiles (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  version integer not null check (version > 0),
  data jsonb not null,
  source_document_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (startup_id, version)
);

------------------------------------------------------------------------------
-- assessments (spec 6.2)
------------------------------------------------------------------------------
create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  knowledge_profile_id uuid references public.knowledge_profiles (id) on delete set null,
  overall_score integer not null check (overall_score between 0 and 100),
  band text not null check (band in ('not_ready', 'getting_there', 'nearly_ready', 'investor_ready')),
  dimension_scores jsonb not null,
  strengths jsonb not null default '[]',
  weaknesses jsonb not null default '[]',
  recommended_actions jsonb not null default '[]',
  rubric_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists assessments_startup_id_created_at_idx on public.assessments (startup_id, created_at desc);
create index if not exists assessments_knowledge_profile_id_idx on public.assessments (knowledge_profile_id);

------------------------------------------------------------------------------
-- simulations (spec 6.3)
------------------------------------------------------------------------------
create table if not exists public.simulations (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  persona text not null check (persona in ('seed_vc', 'angel', 'grant_evaluator')),
  difficulty text not null check (difficulty in ('friendly', 'analytical', 'tough')),
  funding_type text,
  status text not null default 'active' check (status in ('active', 'completed', 'abandoned')),
  current_round integer not null default 1 check (current_round between 1 and 10),
  overall_score integer check (overall_score between 0 and 100),
  investor_confidence text check (investor_confidence in ('low', 'medium', 'high')),
  final_evaluation jsonb,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists simulations_startup_id_created_at_idx on public.simulations (startup_id, created_at desc);

create table if not exists public.simulation_turns (
  id uuid primary key default gen_random_uuid(),
  simulation_id uuid not null references public.simulations (id) on delete cascade,
  turn_index integer not null check (turn_index >= 0),
  round integer not null check (round between 1 and 10),
  role text not null check (role in ('investor', 'founder', 'system')),
  content text not null,
  evaluation jsonb,
  red_flags jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (simulation_id, turn_index)
);

create table if not exists public.red_flags (
  id uuid primary key default gen_random_uuid(),
  simulation_id uuid not null references public.simulations (id) on delete cascade,
  turn_id uuid references public.simulation_turns (id) on delete cascade,
  type text not null check (type in ('contradiction', 'unsupported_claim', 'weak_answer', 'missing_info')),
  severity text not null check (severity in ('low', 'medium', 'high')),
  description text not null,
  evidence jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists red_flags_simulation_id_idx on public.red_flags (simulation_id);
create index if not exists red_flags_turn_id_idx on public.red_flags (turn_id);

------------------------------------------------------------------------------
-- reports (spec 6.4)
------------------------------------------------------------------------------
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  startup_id uuid not null references public.startups (id) on delete cascade,
  assessment_id uuid references public.assessments (id) on delete set null,
  simulation_id uuid references public.simulations (id) on delete set null,
  content jsonb not null,
  pdf_storage_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists reports_startup_id_idx on public.reports (startup_id);
create index if not exists reports_assessment_id_idx on public.reports (assessment_id);
create index if not exists reports_simulation_id_idx on public.reports (simulation_id);

------------------------------------------------------------------------------
-- payments & subscriptions (spec 7). Written only by the server.
------------------------------------------------------------------------------
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  provider text not null default 'paystack' check (provider in ('paystack')),
  reference text not null unique,
  amount_kobo bigint not null check (amount_kobo >= 0),
  currency char(3) not null default 'NGN',
  product text not null check (product in ('pro_monthly', 'credits_3', 'credits_10')),
  status text not null default 'pending' check (status in ('pending', 'success', 'failed', 'abandoned', 'reversed')),
  raw_event jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists payments_user_id_idx on public.payments (user_id);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  provider_subscription_code text unique,
  status text not null check (status in ('active', 'non_renewing', 'attention', 'cancelled', 'completed')),
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists subscriptions_user_id_idx on public.subscriptions (user_id);

------------------------------------------------------------------------------
-- ai_calls: cost tracking. user_id is nulled on account deletion so aggregate
-- cost history survives without being linked to a person. No founder content
-- is stored here.
------------------------------------------------------------------------------
create table if not exists public.ai_calls (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles (id) on delete set null,
  purpose text not null,
  model text not null,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  latency_ms integer check (latency_ms >= 0),
  success boolean not null,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ai_calls_user_id_created_at_idx on public.ai_calls (user_id, created_at desc);
create index if not exists ai_calls_created_at_idx on public.ai_calls (created_at desc);

------------------------------------------------------------------------------
-- audit_logs: survives actor deletion (actor_id is nulled).
------------------------------------------------------------------------------
create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles (id) on delete set null,
  action text not null,
  target_type text,
  target_id uuid,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists audit_logs_actor_id_idx on public.audit_logs (actor_id);
create index if not exists audit_logs_created_at_idx on public.audit_logs (created_at desc);

------------------------------------------------------------------------------
-- updated_at triggers on every table
------------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'startups', 'documents', 'knowledge_profiles', 'assessments',
    'simulations', 'simulation_turns', 'red_flags', 'reports', 'payments',
    'subscriptions', 'ai_calls', 'audit_logs'
  ] loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format(
      'create trigger set_updated_at before update on public.%I
         for each row execute function private.set_updated_at()', t);
  end loop;
end;
$$;

------------------------------------------------------------------------------
-- Create a profile automatically when an auth user signs up.
------------------------------------------------------------------------------
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, nullif(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

-- ===== 20261001000300_rls.sql =====
-- Row Level Security (spec section 8).
--
-- Access model:
--   * Founders (role `authenticated`) can only see rows they own.
--   * Founders may directly write only what they author: their profile's
--     editable fields, their startups, and their document records.
--   * Everything derived by the app (extractions, scores, simulations,
--     reports), all billing state, AI usage and audit logs are written only by
--     server code using the service role, which bypasses RLS.
--   * Admin views read through the service role on the server; there are no
--     admin RLS policies, so an `admin` profile gets no extra access from the
--     browser.
--   * `anon` has no table access at all.

------------------------------------------------------------------------------
-- Ownership helpers. SECURITY DEFINER so policies on child tables do not
-- recurse through the startups policy; each checks auth.uid() explicitly.
------------------------------------------------------------------------------
create or replace function private.owns_startup(p_startup_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.startups s
    where s.id = p_startup_id and s.owner_id = (select auth.uid())
  );
$$;

create or replace function private.owns_simulation(p_simulation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.simulations sim
    join public.startups s on s.id = sim.startup_id
    where sim.id = p_simulation_id and s.owner_id = (select auth.uid())
  );
$$;

revoke all on function private.owns_startup(uuid) from public;
revoke all on function private.owns_simulation(uuid) from public;
grant execute on function private.owns_startup(uuid) to authenticated;
grant execute on function private.owns_simulation(uuid) to authenticated;
revoke all on function private.set_updated_at() from public;
revoke all on function private.handle_new_user() from public;

------------------------------------------------------------------------------
-- Enable RLS everywhere and reset privileges to least privilege.
------------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'startups', 'documents', 'knowledge_profiles', 'assessments',
    'simulations', 'simulation_turns', 'red_flags', 'reports', 'payments',
    'subscriptions', 'ai_calls', 'audit_logs'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant all on public.%I to service_role', t);
  end loop;
end;
$$;

------------------------------------------------------------------------------
-- profiles: read own; update only non-privileged columns.
-- role, plan and credits can never be changed from the browser.
------------------------------------------------------------------------------
grant select on public.profiles to authenticated;
grant update (full_name, country, onboarding_complete) on public.profiles to authenticated;

drop policy if exists "profiles: owner can read" on public.profiles;
create policy "profiles: owner can read"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()));

drop policy if exists "profiles: owner can update" on public.profiles;
create policy "profiles: owner can update"
  on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

------------------------------------------------------------------------------
-- startups: full CRUD on own rows.
------------------------------------------------------------------------------
grant select, insert, update, delete on public.startups to authenticated;

drop policy if exists "startups: owner can read" on public.startups;
create policy "startups: owner can read"
  on public.startups for select to authenticated
  using (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can insert" on public.startups;
create policy "startups: owner can insert"
  on public.startups for insert to authenticated
  with check (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can update" on public.startups;
create policy "startups: owner can update"
  on public.startups for update to authenticated
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

drop policy if exists "startups: owner can delete" on public.startups;
create policy "startups: owner can delete"
  on public.startups for delete to authenticated
  using (owner_id = (select auth.uid()));

------------------------------------------------------------------------------
-- documents: read and delete own. Inserts and status updates happen on the
-- server after the file's content type has been validated.
------------------------------------------------------------------------------
grant select, delete on public.documents to authenticated;

drop policy if exists "documents: owner can read" on public.documents;
create policy "documents: owner can read"
  on public.documents for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "documents: owner can delete" on public.documents;
create policy "documents: owner can delete"
  on public.documents for delete to authenticated
  using ((select private.owns_startup(startup_id)));

------------------------------------------------------------------------------
-- Derived, startup-scoped data: read-only for the owner.
------------------------------------------------------------------------------
grant select on public.knowledge_profiles, public.assessments,
  public.simulations, public.reports to authenticated;

drop policy if exists "knowledge_profiles: owner can read" on public.knowledge_profiles;
create policy "knowledge_profiles: owner can read"
  on public.knowledge_profiles for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "assessments: owner can read" on public.assessments;
create policy "assessments: owner can read"
  on public.assessments for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "simulations: owner can read" on public.simulations;
create policy "simulations: owner can read"
  on public.simulations for select to authenticated
  using ((select private.owns_startup(startup_id)));

drop policy if exists "reports: owner can read" on public.reports;
create policy "reports: owner can read"
  on public.reports for select to authenticated
  using ((select private.owns_startup(startup_id)));

grant select on public.simulation_turns, public.red_flags to authenticated;

drop policy if exists "simulation_turns: owner can read" on public.simulation_turns;
create policy "simulation_turns: owner can read"
  on public.simulation_turns for select to authenticated
  using ((select private.owns_simulation(simulation_id)));

drop policy if exists "red_flags: owner can read" on public.red_flags;
create policy "red_flags: owner can read"
  on public.red_flags for select to authenticated
  using ((select private.owns_simulation(simulation_id)));

------------------------------------------------------------------------------
-- Billing: read own history; written only by the server (Paystack webhook).
------------------------------------------------------------------------------
grant select on public.payments, public.subscriptions to authenticated;

drop policy if exists "payments: owner can read" on public.payments;
create policy "payments: owner can read"
  on public.payments for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "subscriptions: owner can read" on public.subscriptions;
create policy "subscriptions: owner can read"
  on public.subscriptions for select to authenticated
  using (user_id = (select auth.uid()));

-- ai_calls and audit_logs: no policies => no access except service role.

-- ===== 20261001000400_storage.sql =====
-- Private storage buckets (spec sections 3, 6.5, 8).
-- Object paths are `{owner_id}/{startup_id}/{file}` so ownership can be
-- checked from the first path segment.
-- Uploads and deletes go through server code (service role) after content
-- validation; founders may only read their own objects, which is what creating
-- a short-lived signed URL with their session requires.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('documents', 'documents', false, 20971520, array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]),
  ('reports', 'reports', false, 20971520, array['application/pdf'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "documents bucket: owner can read" on storage.objects;
create policy "documents bucket: owner can read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "reports bucket: owner can read" on storage.objects;
create policy "reports bucket: owner can read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'reports'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- ===== 20261001000500_admin.sql =====
-- Admin role seeding. Admin access is enforced server-side by checking
-- profiles.role; this function is the supported way to grant it.
-- Run from the Supabase SQL editor (as postgres):
--   select private.set_user_role('you@example.com', 'admin');
-- or with `npm run db:seed-admin -- you@example.com`.

create or replace function private.set_user_role(p_email text, p_role text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
begin
  if p_role not in ('founder', 'admin') then
    raise exception 'invalid role: %', p_role;
  end if;

  select u.id into v_user_id
  from auth.users u
  where lower(u.email) = lower(p_email);

  if v_user_id is null then
    raise exception 'no user with email %', p_email;
  end if;

  update public.profiles set role = p_role where id = v_user_id;

  insert into public.audit_logs (actor_id, action, target_type, target_id, metadata)
  values (null, 'profile.role_changed', 'profile', v_user_id, jsonb_build_object('role', p_role));

  return v_user_id;
end;
$$;

revoke all on function private.set_user_role(text, text) from public;

-- ===== 20261001000600_backfill_profiles.sql =====
-- Create profiles for any auth users that signed up before the profiles table
-- and its sign-up trigger existed. Safe to run more than once.
insert into public.profiles (id, full_name)
select u.id, nullif(u.raw_user_meta_data ->> 'full_name', '')
from auth.users u
on conflict (id) do nothing;

-- Ask the Supabase Data API to pick up the new tables immediately.
notify pgrst, 'reload schema';

-- ===== Check =====
select
  (select count(*) from pg_tables where schemaname = 'public') as tables_created,
  (select count(*) from public.profiles) as profiles,
  (select count(*) from storage.buckets where id in ('documents', 'reports')) as buckets,
  case
    when (select count(*) from pg_tables where schemaname = 'public') >= 13
     and (select count(*) from storage.buckets where id in ('documents', 'reports')) = 2
    then 'SETUP COMPLETE'
    else 'SETUP INCOMPLETE - send this to Claude'
  end as result;
