#!/usr/bin/env bash
# Bundles every migration into supabase/setup.sql: one file to paste into the
# Supabase SQL Editor when not using the Supabase CLI. Safe to run repeatedly.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/supabase/setup.sql"
{
  echo "-- RaiseReady database setup. Paste ALL of this into the Supabase SQL Editor and click Run."
  echo "-- Generated by scripts/build-setup-sql.sh from supabase/migrations. Safe to run more than once."
  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo
    echo "-- ===== $(basename "$f") ====="
    cat "$f"
  done
  cat <<'SQL'

-- ===== Check =====
select
  (select count(*) from pg_tables where schemaname = 'public') as tables_created,
  (select count(*) from public.profiles) as profiles,
  (select count(*) from storage.buckets where id in ('documents', 'reports')) as buckets,
  case
    when (select count(*) from pg_tables where schemaname = 'public') >= 13
     and (select count(*) from storage.buckets where id in ('documents', 'reports')) = 2
    then 'SETUP COMPLETE'
    else 'SETUP INCOMPLETE - send this to Claude'
  end as result;
SQL
} > "$OUT"
echo "Wrote $OUT"
